# Generated by Django 3.2 on 2021-04-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodel',
            name='cpi',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
